### ISSUE TITLE
latest update error

### ISSUE THREAD

**Issue by Laern2Do** [Arthur-Milchior/anki-number-of-selected-tags#10]
when restoring the config. back to default and hit okie, it throws up this error message

anki 2.1.22, window 10

![image](https://user-images.githubusercontent.com/63658303/86173864-49b40380-bae6-11ea-933d-c0542d13504f.png)

thx!

**Comment by Arthur-Milchior** [comment]
Of course it does. What a nightmare, I'll need to update all schemas to allow for shortcut with two successive keys. Sorry, I'll correct that

**Comment by Laern2Do** [comment]
look like it is working now. thx you!
