### ISSUE TITLE
Add-On Not Working in Anki 2.49

### ISSUE THREAD

**Issue by jtylerhartley** [Arthur-Milchior/anki-number-of-selected-tags#13]
I tried using the Add-On but all I got was this little box with no info displayed. 

![CleanShot 2022-04-09 at 10 50 57](https://user-images.githubusercontent.com/70040274/162579293-b07a903c-e9b1-47b3-81b5-31f7f26389b2.png)

**Comment by akavi1** [comment]
I had this problem too. The box is just too small. Grab the edges and pull it to make the window bigger and reveal the content

**Comment by jtylerhartley** [comment]
Thank you. Your suggestion fixed the issue for me.
