### ISSUE TITLE
I would LOVE to see this function 02

### ISSUE THREAD

**Issue by DoctorToBeIn23** [Arthur-Milchior/anki-number-of-selected-tags#3]
It would be nice if you could define right before which tag that is highlighted that also has a percent greater than the defined value to be able to get boxed... Does this make sense?

![image](https://user-images.githubusercontent.com/60248099/79793224-6fb27000-830d-11ea-928b-d017a5683cae.png)
![image](https://user-images.githubusercontent.com/60248099/79793252-793bd800-830d-11ea-980e-57f25243a082.png)

**Comment by Arthur-Milchior** [comment]
What means "get boxed" ? 
Seems doable

**Comment by DoctorToBeIn23** [comment]
"get boxed" like in the image there is a yellow box around any percentage over the defined percentage. A highligh would be sufficient as well :)

**Comment by Arthur-Milchior** [comment]
Done. Please update and let me know if it's allright

**Comment by Arthur-Milchior** [comment]
FYI I spent a little less than an hour on it

**Comment by DoctorToBeIn23** [comment]
Looks like it working, it does create a large space between lines now if its above the percent and it gets boxed... 

Would it be feasible and simple to code it to have it closer together like the image above? 
Would highlighting the entire row or the percent instead of boxing it not produce the large spaces between lines?

Does that make sense?

**Comment by DoctorToBeIn23** [comment]
Also its only suppose to make a box around it if it is highlighted AND it has the value greater than the defined percentage.

![image](https://user-images.githubusercontent.com/60248099/80012882-40297200-848b-11ea-826b-74a5e116b6bf.png)

**Comment by Arthur-Milchior** [comment]
Please update and let me know if it's better. otherwise, if you know a little bit of html (that's the case of @ankingmed ) can you please give me the style/html you want for the yellow box. (You can give me any css you want, I can just give a name to this table case)

**Comment by DoctorToBeIn23** [comment]
Works great, looks great!!! Have you been able to look at the other aspect
of what I want added with the filtered deck option?

**Comment by Arthur-Milchior** [comment]
Not yet. I have another client right now

**Comment by DoctorToBeIn23** [comment]
Okay when you are able to do that let me know and then let me know how much
total time you put into it for these two updates
