### ISSUE TITLE
High Yield Tags fails to load

### ISSUE THREAD

**Issue by LopezGH** [Arthur-Milchior/anki-number-of-selected-tags#4]
Hello, 

I have no idea what's going on but every time I try to launch Anki I get this error:
![Annotation 2020-04-28 143306](https://user-images.githubusercontent.com/64455219/80447627-41f8a700-895d-11ea-9378-9a08bf923bbe.png)

Any help is much appreciated.

Thanks,
Jay.

**Comment by Arthur-Milchior** [comment]
Which Anki version please ?

**Comment by LopezGH** [comment]
Silly me, forgot to add that, I'm on version 2.1.21 (f1734a47)

**Comment by Arthur-Milchior** [comment]
Please update

**Comment by LopezGH** [comment]
I've updated to 2.1.22 and it seems to have fixed the problem. Loving the addon, thanks so much for your help!

**Comment by Arthur-Milchior** [comment]
I meant: «please update your add-ons». But updating anki works too I guess
