### ISSUE TITLE
Filtered deck can have a maximum of 100 cards

### ISSUE THREAD

**Issue by Farinata** [Arthur-Milchior/anki-number-of-selected-tags#6]
For some reason the created filtered decks based on tags selection can now have a maximum of 100 cards, even if the cards with these tags are more than 100.
Although previously I had no problem with that. It may be due to a new update?

**Comment by Arthur-Milchior** [comment]
The new update just added the notion of "creating a filtered deck", so I can't imagine how this could introduce a new bug to a feature which did not exist.
You may just want to change the filtered deck parameter; this is one of the options

**Comment by Farinata** [comment]
Yes, I just figured out, after I create the deck I need to go to the deck options and set the "limit to" to 9999 for example, then click rebuild; then all the cards will be included.

**Comment by Arthur-Milchior** [comment]
What do you mean by "previously" ? It's a new feature added 6 days ago. And there was no change since this feature was added.

**Comment by Farinata** [comment]
After today's update all works fine. Thanks.
